# Generated by Django 2.2 on 2019-12-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Text')),
                ('author', models.CharField(max_length=20, verbose_name='Added by')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed')], default='new', max_length=20, verbose_name='Status')),
                ('rating', models.IntegerField(default=0, verbose_name='Raiting')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added date')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
        ),
    ]
